[package]
name = "posixutils-file"
version = "0.1.8"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap.workspace = true
gettext-rs.workspace = true
libc.workspace = true
atty = "0.2"
num-traits = "0.2.18"
regex = "1.10"

[[bin]]
name = "cat"
path = "src/cat.rs"

[[bin]]
name = "cmp"
path = "src/cmp.rs"

[[bin]]
name = "cp"
path = "src/cp.rs"

[[bin]]
name = "dd"
path = "src/dd.rs"

[[bin]]
name = "split"
path = "src/split.rs"

[[bin]]
name = "tee"
path = "src/tee.rs"

[[bin]]
name = "file"
path = "src/file.rs"
